name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Ensure latest version

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x gradlew  # Fix permission issue

      - name: Run Lint
        run: ./gradlew lint

      - name: Upload lint test report
        uses: actions/upload-artifact@v4
        with:
          name: lint.html
          path: app/build/reports/lint-results-freeDebug.html

  unit-test:
    needs: [ lint ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Ensure latest version
      - name: Grant execute permission to Gradle wrapper
        run: chmod +x gradlew  # Fix permission issue
      - name: Run tests
        run: ./gradlew test

      - name: Upload html test report
        uses: actions/upload-artifact@v4
        with:
            name: unit_test_report
            path: app/build/reports/testFreeDebugUnitTest